In [11]:
class Employee:
    def __init__(self,ids,name,age):
        self.ids=ids
        self.name=name
        self.age=age
    def show(self):
        print('Employee: ',self.ids,self.name,self.age)       

In [12]:
#inheritance
class Salary(Employee):
    def __init__(self, ids, name, age,salary):
        super().__init__(ids,name, age)
        self.salary=salary
        
    def showSalary(self):
        print(self.name,self.salary)

In [13]:
obj=Salary(101,'chandan',21,21500)
obj.showSalary()


chandan 21500


In [55]:
#encapsulation
class Salary1(Employee):
    def __init__(self, ids, name, age,salary):
        super().__init__()
        self.__salary=salary
        
    def showSalary(self):
        print(self.name,self.salary)


In [27]:
obj=Salary1(101,'chandan',21,21500)
print(obj.__salary)
#salary cannot be accessed outside the class

AttributeError: 'Salary1' object has no attribute 'salary'

In [28]:
#PolyMorphism

class Circle:
    pi = 3.14
    def __init__(self, redius):
        self.radius = redius

    def calculate_area(self):
        print("Area of circle :", self.pi * self.radius * self.radius)

class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width
    def calculate_area(self):
        print("Area of Rectangle :", self.length * self.width)

# function
def area(shape):
    shape.calculate_area()


cir = Circle(5)
rect = Rectangle(10, 5)

# call common function
area(cir)
area(rect)


Area of circle : 78.5
Area of Rectangle : 50


In [44]:
import numpy as np
#1D-Array
arr = np.array([1, 2, 3, 4])
print(arr[2])

3


In [49]:
#2D-Array
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2[1,3])
#negative indexing
print(arr2[-2,-1])

9
5


In [46]:
#3D-Array
arr3= np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3[0, 1, 2])

6


In [53]:
#Slicing 1D Array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])
print(arr[3:-2])
print(arr[1:-3])
print(arr[:-1])
print(arr[1:5:2])

[5 6 7]
[4 5]
[2 3 4]
[1 2 3 4 5 6]
[2 4]


In [54]:
#Slicing 2D Array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])


[7 8 9]


In [15]:
#Composistion
class one:
    def __init__(self,name):
        self.name=name
    def onefun(self):
        print(self.name)
class two:
    def __init__(self,age):
        self.age=age
        self.test=one("chandan")
        self.test.onefun()
    def twofun(self):
        print(self.age)

t=two(22)
t.twofun()
        

chandan
22


In [21]:
#Aggregation
class one:
    def __init__(self,name):
        self.name=name
    def onefun(self):
        print(self.name)
class two:
    def __init__(self,age,fobj):
        self.age=age
        self.test=fobj
        self.test.onefun()
    def twofun(self):
        print(self.age)

fobj=one("hello")
t=two(22,fobj)
t.twofun()

hello
22


In [29]:
class A:
    def fun(self):
        print("hello A")
        
class B(A):
    def fun(self):
        print("hello B")
        
class C(A):
    def fun(self):
        print("hello C")

class D(B,C):
    def fun(self):
        print("hello D")
        
obj=D()
obj.fun()
        

hello D


In [38]:
class A:
    def fun(self):
        print("hello A")
        
class B(A):
    def fun(self):
        print("hello B")
        
class C(A):
    def fun(self):
        print("hello C")

class D(B,C):
    pass
#     def fun(self):
        
        
obj=D()
obj.fun()    

hello B


In [66]:
import pandas as pd
df=pd.DataFrame({
    'name':['alice','bob','charlie'],
    'date_of_birth':['10/25/2005','10/29/2002','01/01/2001']
})
print(df)
df['date_of_birth']=pd.to_datetime(df['date_of_birth'])
print(df)
df['date_of_birth']=pd.to_datetime(df['date_of_birth'],format='%D/%m/%Y')
print(df)


SyntaxError: invalid syntax (<ipython-input-66-184ac77a6c27>, line 12)

In [123]:
import datetime
df=pd.DataFrame({
    'name':['alice','bob','charlie'],
    'age':[12,34,53]
})

df["timestamp_col"]=pd.Timestamp(datetime.datetime.now())
df["formatted_col"]=df["timestamp_col"].map(lambda ts:ts.strftime("%d-%m-%Y"))
print(df)

      name  age              timestamp_col formatted_col
0    alice   12 2022-05-16 12:03:32.523056    16-05-2022
1      bob   34 2022-05-16 12:03:32.523056    16-05-2022
2  charlie   53 2022-05-16 12:03:32.523056    16-05-2022


In [124]:
df[df['timestamp_col']<pd.Timestamp(datetime.datetime(2022,5,17))]


name  age              timestamp_col formatted_col
0    alice   12 2022-05-16 12:03:32.523056    16-05-2022
1      bob   34 2022-05-16 12:03:32.523056    16-05-2022
2  charlie   53 2022-05-16 12:03:32.523056    16-05-2022

In [128]:
df=pd.DataFrame({
    'name':['alice','bob','charlie'],
    'date_of_birth':['10/25/2005','10/29/2002','01/01/2001']
})
print(type(df['date_of_birth']))
df['date_of_birth']=pd.to_datetime(df['date_of_birth'])
op=df[df['date_of_birth']<pd.Timestamp(datetime.datetime(2022,5,17))]
o7p

<class 'pandas.core.series.Series'>


name date_of_birth
0    alice    2005-10-25
1      bob    2002-10-29
2  charlie    2001-01-01

In [112]:
class Employee:
    def __init__(self,ids,name,age):
        self.ids=ids
        self.name=name
        self.age=age
    def show(self):
        print('Employee: ',self.ids,self.name,self.age)   
class Salary(Employee):
    def __init__(self, ids, name, age,salary):
        super().__init__( ids, name, age)
        self.salary=salary
        
    def showSalary(self):
        print('Name: ',self.name,'Salary: ',self.salary)
obj=Salary(101,'chandan',21,21500)
obj.showSalary()

Name:  chandan Salary:  21500


In [106]:
class Employee:
    def __init__(self,ids,name,age):
        self.ids=ids
        self.name=name
        self.age=age
    def show(self):
        print('Employee: ',self.ids,self.name,self.age)   
        
class Salary(Employee): #Single-Level Inheritance
    def __init__(self, ids, name, age,salary):
        super().__init__( ids, name, age)
        self.salary=salary
        
    def showSalary(self):
        print('Name: ',self.name,'Salary: ',self.salary)
        
class ERank(Salary):  #Multi-Level Inheritance
    def __init__(self,rank):
        
        super().__init__(101,"chandan",34,23666)
        self.rank=rank
        
    def showRank(self):
        print('Name: ',self.name,'Salary: ',self.salary,'Rank: ',self.rank)
        
obj=ERank(1)
obj.showRank()

Name:  chandan Salary:  23666 Rank:  1


In [130]:
df = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3', 'K4', 'K5'],
                   'A': ['A0', 'A1', 'A2', 'A3', 'A4', 'A5']})
df

key   A
0  K0  A0
1  K1  A1
2  K2  A2
3  K3  A3
4  K4  A4
5  K5  A5

In [131]:
other = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                      'B': ['B0', 'B1', 'B2']})
other

key   B
0  K0  B0
1  K1  B1
2  K2  B2

In [137]:
df.join(other, lsuffix='_caller', rsuffix='_other')

key_caller   A key_other    B
0         K0  A0        K0   B0
1         K1  A1        K1   B1
2         K2  A2        K2   B2
3         K3  A3       NaN  NaN
4         K4  A4       NaN  NaN
5         K5  A5       NaN  NaN

In [138]:
df.join(other, how='right', lsuffix='_caller', rsuffix='_other')

key_caller   A key_other   B
0         K0  A0        K0  B0
1         K1  A1        K1  B1
2         K2  A2        K2  B2

In [140]:
df.join(other, how='inner', lsuffix='_caller', rsuffix='_other')

key_caller   A key_other   B
0         K0  A0        K0  B0
1         K1  A1        K1  B1
2         K2  A2        K2  B2